- name: Show version from Cisco IOS devices
  hosts: cisco_ios
  gather_facts: false
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_version

    - name: Print output
      ansible.builtin.debug:
        var: show_version.stdout_lines

